MoviePlex.UI/Controllers/FilmController.cs
using Microsoft.AspNetCore.Mvc;
using MoviePlex.Core.Areas.Films;
using MoviePlex.Core.Areas.Films.Dtos;
using MoviePlex.Core.Areas.Validators;
using MoviePlex.UI.Utilities;

namespace MoviePlex.UI.Controllers;

public class FilmController : Controller
{
    private readonly IFilmService _filmService;
    private readonly IValidationService _validationService;
    
    public FilmController(IFilmService filmService, IValidationService validationService)
    {
        _filmService = filmService;
        _validationService = validationService;
    }
    
    
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public ActionResult AdminPanel()
    {
        return View();
    }

    [HttpGet]
    public async Task<ActionResult> GetListAdminAsync()
    {
        var films = await _filmService.GetListAsync();
        
        return View(films);
    }
    
    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<ActionResult> CreateAsync(FilmInputDto filmInput)
    {
        var result = await _validationService.ValidateAsync(filmInput);
        if (! result.IsValid)
        {
            result.AddToModelState(ModelState);
            
            return View(filmInput);
        }
        
        await _filmService.CreateAsync(filmInput);
        
        return RedirectToAction("GetListAdmin");
    }
    
    public async Task<ActionResult> EditAsync(int id)
    {
        var film = await _filmService.GetInputDtoByIdAsync(id);
        
        return View(film);
    }

    [HttpPost]
    public async Task<ActionResult> EditAsync(int id, FilmInputDto filmInput)
    {
        var result = await _validationService.ValidateAsync(filmInput);
        if (! result.IsValid)
        {
            result.AddToModelState(ModelState);
            
            return View(filmInput);
        }
        
        await _filmService.UpdateByIdAsync(id, filmInput);
        
        return RedirectToAction("GetListAdmin");
    }
    
    [HttpDelete]
    public async Task<ActionResult> DeleteAsync(int id)
    {
        await _filmService.DeleteByIdAsync(id);
        
        return RedirectToAction("GetListAdmin");
    }
}

MoviePlex.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MoviePlex.UI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
}

MoviePlex.UI/Views/Film/AdminPanel.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<br/>
<h2>This is Admin Panel</h2>
<br/>

<a class="nav-link" asp-controller="Film" asp-action="GetListAdmin">Film list</a>
<a class="nav-link" asp-controller="Film" asp-action="Create">Create Film</a>

MoviePlex.UI/Views/Film/Create.cshtml
@model MoviePlex.Core.Areas.Films.Dtos.FilmInputDto;

@{
    ViewBag.Title = "Create Film";
    Layout = "_Layout";
}


@using (Html.BeginForm("Create", "Film", FormMethod.Post))
{
    await Html.RenderPartialAsync("PartialViews/InputForm");
}

MoviePlex.UI/Views/Film/Delete.cshtml
@model MoviePlex.Core.Areas.Films.Dtos.FilmDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

MoviePlex.UI/Views/Film/Edit.cshtml
@model MoviePlex.Core.Areas.Films.Dtos.FilmInputDto;

@{
    ViewBag.Title = "Edit Film";
    Layout = "_Layout";
}


@using (Html.BeginForm("Edit", "Film", FormMethod.Post))
{
    await Html.RenderPartialAsync("PartialViews/InputForm");
}

MoviePlex.UI/Views/Film/GetListAdmin.cshtml
@model System.Collections.Generic.List<MoviePlex.Core.Areas.Films.Dtos.FilmDto>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>List all Films</h2>
<br/>
<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Duration</th>
        <th scope="col">Rental Start Date</th>
        <th scope="col">Rental End Date</th>
        <th scope="col">Publisher</th>
        <th scope="col">Genre</th>
        <th scope="col">Trailer</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var film in Model)
    {
        <tr>
            <td>@film.Name</td>
            <td>@film.Duration</td>
            <td>@film.RentalStartDate.ToString("dd/MM/yyyy")</td>
            <td>@film.RentalEndDate.ToString("dd/MM/yyyy")</td>
            <td>@film.Publisher</td>
            <td>@film.Genre</td>
            <td>
                <a href="@film.Trailer">Watch Trailer</a>
            </td>
            <td>
                <a href="/Film/Edit/@film.Id">
                    <i class="bi bi-pencil">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg>
                    </i>
                </a>
            </td>
            <td>
                <a onclick="confirmDelete(@film.Id)" class="link-icon">
                    <i class="bi bi-trash3-fill">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                            <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                        </svg>
                    </i>
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

<script>
    function confirmDelete(filmId) {
        var confirmation = confirm("Are you sure you want to delete this film?");

        if (confirmation) {
            deleteFilm(filmId);
        }
    }

    function deleteFilm(filmId) {
        $.ajax({
            url: '/Film/Delete',
            type: 'Delete',
            data: { id: filmId },
            success: function () {
                // location.reload();
            },
            error: function () {
                location.reload();
            }
        });
    }
</script>

MoviePlex.UI/Views/Film/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Film Index</h2>

MoviePlex.UI/Views/Film/PartialViews/InputForm.cshtml
@model MoviePlex.Core.Areas.Films.Dtos.FilmInputDto;

@Html.ValidationSummary(true)
<fieldset>
    <legend>Create Film</legend>
    <div class="form-group">
        <label for="Name" class="form-label mt-4">Name</label>
        <input type="text" class="form-control" asp-for="Name" placeholder="Enter name">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label for="Duration" class="form-label mt-4">Duration</label>
        <input type="time" class="form-control" asp-for="Duration" placeholder="Enter duration">
        <span asp-validation-for="Duration"></span>
    </div>
    <div class="form-group">
        <label for="RentalStartDate" class="form-label mt-4">Rental Start Date</label>
        <input type="date" class="form-control" asp-for="RentalStartDate" placeholder="Enter rental start date">
        <span class="text-danger" asp-validation-for="RentalStartDate"></span>
    </div>
    <div class="form-group">
        <label for="RentalEndDate" class="form-label mt-4">Rental End Date</label>
        <input type="Date" class="form-control" asp-for="RentalEndDate" placeholder="Enter rental end date">
        <span class="text-danger" asp-validation-for="RentalEndDate"></span>
    </div>
    <div class="form-group">
        <label for="Publisher" class="form-label mt-4">Publisher</label>
        <input type="text" class="form-control" asp-for="Publisher" placeholder="Enter publisher">
        <span class="text-danger" asp-validation-for="Publisher"></span>
    </div>
    <div class="form-group">
        <label for="Genre" class="form-label mt-4">Genre</label>
        <select class="form-select" asp-for="Genre">
            <option value="1">Comedy</option>
            <option value="2">Drama</option>
            <option value="3">History</option>
            <option value="4">Horror</option>
            <option value="99">Other</option>
        </select>
        <span class="text-danger" asp-validation-for="Genre"></span>
    </div>
    <div class="form-group">
        <label for="Trailer" class="form-label mt-4">Trailer</label>
        <input type="text" class="form-control" asp-for="Trailer" placeholder="Enter url on trailer">
        <span class="text-danger" asp-validation-for="Trailer"></span>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
</fieldset>

MoviePlex.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}

<div class="container">
    <br>
    <h1 class="display-10">Welcome to our website!</h1>
    <p class="lead">Here you can book tickets to our movie theater, for the movies you are interested in.</p>
    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

MoviePlex.UI/Views/Shared/_ErrorPartial.cshtml
@{
    var errorMessage = Context.Session.GetString("ErrorMessage");
    Context.Session.Remove("ErrorMessage");
}

@if (!string.IsNullOrEmpty(errorMessage))
{
    <div id="error-message" class="alert alert-danger" role="alert">
        <span>@errorMessage</span>
        <button id="close-error" type="button" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<script>
    document.getElementById("close-error").addEventListener("click", function() 
    {
        document.getElementById("error-message").style.display = "none";
    });
</script>

MoviePlex.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MoviePlex.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/luxStyle.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MoviePlex.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Film" asp-action="Index">Films</a>
                    </li>
                    @* Сделать чтоб показовалось если пользователь Admin *@
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin Panel</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Cinema halls</a>
                            <a class="dropdown-item" asp-controller="Film" asp-action="AdminPanel">Films</a>
                            <a class="dropdown-item" href="#">Sessions</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Mailing</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    @* Сделать чтоб показовалось адекватно когда пользователь зашёл *@
                    <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Register</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @{
            await Html.RenderPartialAsync("_ErrorPartial");
        };

        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>